---
name: Cache Cleanup

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup-caches:
    uses: miikkak/workflows/.github/workflows/cache-cleanup.yml@e1de600c281bb249cfd9c6b2bb3030a2f1ac40b6 # main
    secrets: inherit
