---
name: Cache Cleanup

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup-caches:
    uses: miikkak/workflows/.github/workflows/cache-cleanup.yml@c6c1d2dbf4948b366c7d33022eabffa78cb830d0 # main
    secrets: inherit
