---
name: Cache Cleanup

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup-caches:
    uses: miikkak/workflows/.github/workflows/cache-cleanup.yml@435fab5b6186294629adfd88632790ab0306259f # main
    secrets: inherit
