---
name: Code Review

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

  actions: write
jobs:
  review:
    if: github.event.pull_request.draft == false
    uses: miikkak/workflows/.github/workflows/code-review.yml@e1de600c281bb249cfd9c6b2bb3030a2f1ac40b6 # main
    with:
      enabled: true
    secrets: inherit
