---
name: Code Review

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

  actions: write
jobs:
  review:
    if: github.event.pull_request.draft == false
    uses: miikkak/workflows/.github/workflows/code-review.yml@46dd3e316fb25559d6df15d5aed254d68ba2fd00 # main
    with:
      enabled: true
    secrets: inherit
