---
name: PR Check

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  pre-commit:
    uses: miikkak/workflows/.github/workflows/pr-check.yml@e1de600c281bb249cfd9c6b2bb3030a2f1ac40b6 # main
    secrets: inherit
