---
name: Pre-commit Hook Updates

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 9 * * 1"
  workflow_dispatch:


permissions:
  contents: write
  issues: write
  pull-requests: write

  actions: write
jobs:
  check-updates:
    uses: miikkak/workflows/.github/workflows/precommit-updates.yml@e1de600c281bb249cfd9c6b2bb3030a2f1ac40b6 # main
    secrets: inherit
