---
name: Secret Scan

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  push:
    branches: ["**"]
  schedule:
    # Run daily at 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  secret-scan:
    uses: miikkak/workflows/.github/workflows/secret-scan.yml@e1de600c281bb249cfd9c6b2bb3030a2f1ac40b6 # main
