---
name: Scheduled Security Scan

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  security:
    uses: miikkak/workflows/.github/workflows/security-scan.yml@412b2b8520307f6389466787a6b9007e38027e31 # main
    secrets: inherit
