---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@0e6ac813aa18c152df14b4a8d35c38cbbbfecff4 # main
    secrets: inherit
    with:
      validate-bash: false
      validate-json: true
