---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@c6c1d2dbf4948b366c7d33022eabffa78cb830d0 # main
    secrets: inherit
    with:
      validate-bash: false
      validate-json: true
