---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@c4f96374159bd450f223d2d08f16866dc7608f41 # main
    secrets: inherit
    with:
      validate-bash: false
      validate-json: true
